apiVersion: v1
kind: Pod
metadata:
  name: docling
  labels:
    app: docling
  namespace: tag-ai--pipeline
spec:
  containers:
    - name: docling
      image: images.paas.redhat.com/genie/docling:latest
      #image: 'image-registry.openshift-image-registry.svc:5000/tag-ai--pipeline/docling:test'
      imagePullPolicy: Always
      stdin: true
      tty: true
      resources:
        requests:
          memory: '6Gi' 
          cpu: '4'
          # gpu: '2' #nvidia.com/gpu in the deployment.yaml
        limits:
          memory: '32Gi'
          cpu: '8'
          # gpu: '2' #nvidia.com/gpu in the deployment.yaml
      command: ['/bin/bash']
  tolerations:
    - key: nvidia.com/gpu
      operator: Exists
      effect: NoSchedule
    - key: tenant
      operator: Equal
      value: llmaas-a100
      effect: NoSchedule 