kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: docling
  namespace: tag-ai--pipeline
spec:
  tags:
    - name: latest
      annotations: null
      from:
        kind: DockerImage
        name: images.paas.redhat.com/genie/docling:latest
      generation: 5
      importPolicy:
        importMode: Legacy
      referencePolicy:
        type: Source


