apiVersion: v1
kind: Secret
metadata:
  name: image-paas-registry-sfiresht
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJpbWFnZXMucGFhcy5yZWRoYXQuY29tIjogewogICAgICAiYXV0aCI6ICJKR0Z3Y0RwVU1Ea3pNRXhRVkZGR1REVTJRakJGU3pkT1ZraERUalJLVmxkUVNUSk5RMEZSVDFKWE56QTBRVUpPVDFKU1dqWTRRa3BVVFRBelRqTlJTRFpVVmpaQ1IwbEVTbEpSTmpVek5VbEpVa1UwUzB0RlVWSkxNa2hCVEVGWk0xTkVPREZHT1ZkU1FqRTBNa2swVUZKVldscFNNemxCVkVoWk5ERT0iLAogICAgICAiZW1haWwiOiAiIgogICAgfQogIH0KfQ==
type: kubernetes.io/dockerconfigjson